API:
  NAME: Boilerplate
  PORT: 3100
  URL: http://localhost:3100
  PUBLIC_DIR: public
LOG:
  LOG_DIR: logs
  FILE_NAME: log_file.log
  WHEN: midnight
  INTERVAL: 1
  BACKUP_COUNT: 365
DB_CONNECTION: mysql+pymysql://root:mysql123@localhost:3306/boilerplatedb
JWT_SECRET_KEY: jwt@boilerplate!
MAIL:
  SMTP_SERVER: smtp.gmail.com
  SMTP_PORT: 587
  SENDER_EMAIL: dssama.noreply@gmail.com
  SENDER_PASSWD: hghrcqqnybblklfy